import type { TemplateName, TemplateStyle } from '@/types';

export const templates: Record<TemplateName, TemplateStyle> = {
  classic: {
    name: 'classic',
    label: 'Classic',
    cardBg: 'bg-white',
    cardBorder: 'border border-gray-200',
    cardShadow: 'shadow-lg',
    qrBg: 'bg-white',
    qrColor: '#000000',
    accentColor: 'bg-gray-900',
    textColor: 'text-gray-900',
    subtitleColor: 'text-gray-500',
    iconColor: 'text-gray-400',
  },
  modern: {
    name: 'modern',
    label: 'Modern',
    cardBg: 'bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900',
    cardBorder: 'border border-slate-700/50',
    cardShadow: 'shadow-2xl shadow-slate-900/40',
    qrBg: 'bg-white rounded-lg',
    qrColor: '#0f172a',
    accentColor: 'bg-gradient-to-r from-cyan-500 to-blue-500',
    textColor: 'text-white',
    subtitleColor: 'text-slate-400',
    iconColor: 'text-cyan-400',
  },
  vibrant: {
    name: 'vibrant',
    label: 'Vibrant',
    cardBg: 'bg-gradient-to-br from-violet-600 via-fuchsia-600 to-pink-500',
    cardBorder: 'border border-white/20',
    cardShadow: 'shadow-2xl shadow-fuchsia-500/30',
    qrBg: 'bg-white rounded-lg',
    qrColor: '#7c3aed',
    accentColor: 'bg-white/20 backdrop-blur-sm',
    textColor: 'text-white',
    subtitleColor: 'text-white/70',
    iconColor: 'text-white',
  },
  glassmorphism: {
    name: 'glassmorphism',
    label: 'Glass',
    cardBg: 'bg-white/10 backdrop-blur-xl border border-white/30',
    cardBorder: 'border border-white/30',
    cardShadow: 'shadow-2xl shadow-black/10',
    qrBg: 'bg-white rounded-lg',
    qrColor: '#1e293b',
    accentColor: 'bg-white/20 backdrop-blur-md border border-white/40',
    textColor: 'text-slate-800',
    subtitleColor: 'text-slate-500',
    iconColor: 'text-slate-400',
  },
  minimal: {
    name: 'minimal',
    label: 'Minimal',
    cardBg: 'bg-white',
    cardBorder: 'border border-gray-100',
    cardShadow: 'shadow-sm',
    qrBg: 'bg-gray-50 rounded-lg',
    qrColor: '#374151',
    accentColor: 'bg-gray-100',
    textColor: 'text-gray-700',
    subtitleColor: 'text-gray-400',
    iconColor: 'text-gray-300',
  },
  corporate: {
    name: 'corporate',
    label: 'Corporate',
    cardBg: 'bg-gradient-to-br from-gray-50 to-gray-100',
    cardBorder: 'border border-gray-300',
    cardShadow: 'shadow-lg',
    qrBg: 'bg-white rounded-lg border border-gray-200',
    qrColor: '#1e40af',
    accentColor: 'bg-blue-700',
    textColor: 'text-gray-800',
    subtitleColor: 'text-gray-500',
    iconColor: 'text-blue-600',
  },
};

export const templateKeys: TemplateName[] = ['classic', 'modern', 'vibrant', 'glassmorphism', 'minimal', 'corporate'];
