import { SEOHead } from '@/components/SEOHead';

export default function Terms() {
  return (
    <>
      <SEOHead
        title="Terms of Use — QR Studio"
        description="Terms of use for QR Studio, the free QR code generator. Understand acceptable use, intellectual property, and limitation of liability."
        canonicalUrl="https://qrstudio.app/terms"
      />

      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-8">
        <header>
          <h1 className="text-3xl font-extrabold tracking-tight mb-2">Terms of Use</h1>
          <p className="text-sm text-muted-foreground">Last updated: January 2025</p>
        </header>

        {[
          {
            title: 'Acceptance of terms',
            body: 'By using QR Studio you agree to these terms. If you do not agree, please do not use the service. We may update these terms from time to time; continued use after an update constitutes acceptance of the new terms.',
          },
          {
            title: 'Permitted use',
            body: 'QR Studio is free to use for personal, commercial, and non-commercial purposes. You may download, print, and distribute QR codes generated with QR Studio without restriction. You may not use QR Studio to generate QR codes that link to illegal content, malware, phishing sites, or material that violates applicable laws.',
          },
          {
            title: 'Intellectual property',
            body: 'The QR Studio application, its source code, and branding are the property of their respective owners. QR codes you generate belong to you. We make no claim to the content you encode in your QR codes.',
          },
          {
            title: 'Disclaimer of warranties',
            body: 'QR Studio is provided "as is" without warranty of any kind. We do not guarantee that QR codes generated by the service will scan correctly on all devices or in all environments. Always test your QR codes before printing at scale.',
          },
          {
            title: 'Limitation of liability',
            body: 'To the fullest extent permitted by law, QR Studio shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service, including but not limited to business losses resulting from QR codes that fail to scan.',
          },
          {
            title: 'Contact',
            body: 'Questions about these terms should be directed to contact@qrstudio.app.',
          },
        ].map(section => (
          <section key={section.title} className="space-y-2">
            <h2 className="text-lg font-semibold">{section.title}</h2>
            <p className="text-muted-foreground leading-relaxed text-sm">{section.body}</p>
          </section>
        ))}
      </div>
    </>
  );
}
